
services:
  - type: web
    name: telegram-bot
    env: node
    buildCommand: npm install
    startCommand: node bot/index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
